components:
  Dashboard:
    props:
      user: object
    state:
      data: object
      loading: boolean
    children:
      - Header
      - MainContent
      - Footer

  Header:
    props:
      title: string
      user: object
    lazyLoad: false
    children:
      - UserMenu

  UserMenu:
    props:
      user: object
      menuItems: array
    state:
      isOpen: boolean

  MainContent:
    props:
      user: object
    state:
      posts: array
      loading: boolean
    children:
      - PostList
      - PostDetails

  PostList:
    props:
      posts: array
    lazyLoad: true

  PostDetails:
    props:
      post: object
    lazyLoad: true

  Footer:
    props:
      year: number
      links: array
    lazyLoad: false

  Test:
    lazyLoad: false

hooks:
  useUserData:
    args:
      userId: number
    returns:
      data: object
      loading: boolean
  usePosts:
    args: none
    returns:
      posts: array
      loading: boolean

styles:
  Dashboard:
    css: |
      .dashboard {
        display: flex;
        flex-direction: column;
        height: 100vh;
      }
  Header:
    css: |
      .header {
        background-color: #333;
        color: white;
        padding: 1rem;
      }
  Footer:
    css: |
      .footer {
        background-color: #f1f1f1;
        text-align: center;
        padding: 1rem;
        position: absolute;
        bottom: 0;
        width: 100%;
      }
